### ISSUE TITLE
Unfortunately PieMessage has stopped

### ISSUE THREAD

**Issue by benjyyy** [bboyairwreck/PieMessage#25]
Is anyone getting the same error, how do you fix it?

Thats the error message:

06-05 19:54:17.728 27735-27735/com.ericchee.bboyairwreck.piemessage E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.ericchee.bboyairwreck.piemessage, PID: 27735
                                                                                      java.lang.NoSuchMethodError: android.view.Window.setStatusBarColor
                                                                                          at com.ericchee.bboyairwreck.piemessage.MessageActivity.setStatusBarColor(MessageActivity.java:270)
                                                                                          at com.ericchee.bboyairwreck.piemessage.MessageActivity.onCreate(MessageActivity.java:69)
                                                                                          at android.app.Activity.performCreate(Activity.java:5350)
                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
                                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5322)
                                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by bboyairwreck** [comment]
hmmm that is an odd error. what was the app doing when you got this message. The error message doesnt give much context unfortunately

**Comment by benjyyy** [comment]
I press the plus button
On 9 Jun 2016 08:12, bboyairwreck notifications@github.com wrote:hmmm that is an odd error. what was the app doing when you got this message. The error message doesnt give much context unfortunately
