### ISSUE TITLE
OSX Client Connection Refused

### ISSUE THREAD

**Issue by omarei** [bboyairwreck/PieMessage#31]
Running the Code I get it to start, find the applescript, then JAVA.NET refuses the connection. I checked the ports, and pinged the port and all is fine on the server side. Something here might be amiss. Any ideas? [Terminal Shot Below]

Merci!

```
cd PieMessage/PieOSXClient && gradle run
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
:compileJava
:processResources UP-TO-DATE
:classes
:run
File "/messages.applescript" exists
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at OSXIncomingMessageThread.run(OSXIncomingMessageThread.java:30)
        at java.lang.Thread.run(Thread.java:745)
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at OSXOutgoingMessageThread.run(OSXOutgoingMessageThread.java:25)
        at java.lang.Thread.run(Thread.java:745)

BUILD SUCCESSFUL

Total time: 4.605 secs

```

**Comment by neilio** [comment]
Same issue here.

**Comment by neilio** [comment]
Nevermind, I fixed it - you need to open port 5000 and make sure it's forwarded to the system running PieMessage.

**Comment by omarei** [comment]
@neilio can you tell me how you did that. I posted this so long ago I sorta forgot the flow :p

**Comment by neilio** [comment]
I don't know how your system connects to the internet, but I assume you'd need to open the port on your router.

**Comment by omarei** [comment]
oh yeah! ok i'll give that a try! thanks @neilio
